<h3>Benvenuto nella tua area personale!</h3>
<br class="clr"/>
<?php echo '<p><b>Nome: </b>'.$this->utente->nome.'</p>'; 
 echo '<p><b>Cognome: </b>'.$this->utente->cognome.'</p>'; 
 echo '<p><b>Genere: </b>'.$this->utente->genere.'</p>'; 
 echo '<p><b>Età: </b>'.$this->utente->eta.'</p>';
 echo '<p><b>Email: </b>'.$this->utente->mail.'</p>';
 echo '<p><b>N.Telefono: </b>'.$this->utente->telefono.'</p>'; 
 echo '<p><b>Username: </b>'.$this->utente->username.'</p>'; ?>
 <a class="btn" href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'moddati',
                        'username'   => $this->utente->username,
                        ), 
                        'default',true
                    ); 
                 ?>">Modifica profilo</a>