<h3>Gestisci le promozioni inserite</h3>
<br class="clr"/>
<ul class="thumbnails">
                            <?php foreach ($this->offerte as $offerta) :?>
				<li class="span9">
				  <table class="well">
                                      <tr>
                                        <td class="span3">
					   <img src="<?=$this->baseUrl('img/prodotti/1.jpg')?>"/>
                                        </td>
                                        <td class="span6">
					   <?php echo  '<h5>'.$offerta->nome.'</h5>' ?>
                                          <hr class="soft"/>
					   <?php echo '<p>'.$offerta->descrizione.'</p>'?>
					  <br class="clr"/>
				         </td>
                                      </tr>
                                      <tr>
                                          <td>
                                              <h4><a class="btn" href="<?= $this->url(array(
                                                     'controller' => 'staff',
                                                     'action'     => 'modprom',
                                                     'id'   => $offerta->id,
                                                        ), 
                                                                  'default',true
                                                       ); 
                                                     ?>">Modifica</a>
                                                  <a class="btn" href="<?= $this->url(array(
                                                     'controller' => 'staff',
                                                     'action'     => 'elimina',
                                                     'id'   => $offerta->id,
                                                        ), 
                                                                  'default',true
                                                       ); 
                                                     ?>">Elimina</a>
                                              </h4>
                                          </td>
                                      </tr>
				  </table>
				</li>
                            <?php endforeach ?>
</ul>