<h3>Gestisci le promozioni inserite</h3>
<?php if($this->elimina):?>
<?php echo '<h4 style="color:red">Il prodotto/servizio '.$this->off.' è stato eliminato</h4>'?>
<?php endif ?>
<?php if($this->modifica):?>
<?php echo '<h4 style="color:red">Il prodotto/servizio '.$this->off.' è stato modificato</h4>'?>
<?php endif ?>
<br class="clr"/>
<ul class="thumbnails">
                            <?php foreach ($this->offerte as $offerta) :?>
				<li class="span9">
				  <table class="well">
                                      <tr>
                                        <td class="span3">
					    <?php echo '<img src="' . $this->baseUrl('img/prodotti/'. $offerta->immagine). '"/>' ?>
                                        </td>
                                        <td class="span6">
					   <?php echo  '<h5>'.$offerta->nome.'</h5>' ?>
                                          <hr class="soft"/>
					   <?php echo '<p><b>Descrizione: </b>'.$offerta->descrizione.'</p>'?>
                                           <?php echo '<p><b>Categoria: </b>'.$offerta->categoria.'</p>'?>
                                           <?php echo '<p><b>Azienda: </b>'.$offerta->azienda.'</p>'?>
                                           <?php echo '<p><b>Data inizio: </b>'.$offerta->inizio.'</p>'?>
                                           <?php echo '<p><b>Data fine: </b>'.$offerta->fine.'</p>'?>
                                           <?php echo '<p><b>Prezzo: </b>'.$offerta->prezzo.'€</p>'?>
                                           <?php echo '<p><b>Tipo Sconto: </b>'.$offerta->tipologia.'</p>'?>
					  <br class="clr"/>
				         </td>
                                      </tr>
                                      <tr>
                                          <td>
                                              <h4><a class="btn" href="<?= $this->url(array(
                                                     'controller' => 'staff',
                                                     'action'     => 'modprom',
                                                     'id'   => $offerta->id,
                                                        ), 
                                                                  'default',true
                                                       ); 
                                                     ?>">Modifica</a>
                                                  <a class="btn" href="<?= $this->url(array(
                                                     'controller' => 'staff',
                                                     'action'     => 'elimina',
                                                     'id'   => $offerta->id,
                                                     'nome' => $offerta->nome,
                                                        ), 
                                                                  'default',true
                                                       ); 
                                                     ?>">Elimina</a>
                                              </h4>
                                          </td>
                                      </tr>
				  </table>
				</li>
                            <?php endforeach ?>
</ul>

<div class="centro">
    <div class="pagination">
    <?php if($this->offerte instanceof Zend_Paginator) {
	  		echo $this->paginationControl($this->offerte,'Sliding','staff/_paginator.phtml');
	  } 
          ?>
    </div>
</div>