<div id="mainBody">
	<div class="container">
	<div class="row">
<div id="sidebar" class="span3">
    <div class="well">
        <ul>
            <li><a href="">Profilo personale</a></li>
            <li><a href="">Modifica profilo</a></li>
            <li><a href="">Inserisci nuova promozione</a></li>
            <li><a href="">Gestisci promozioni</a></li>
        </ul>
    </div>
    
</div>

<div class="span9">
   <?php echo $this->inserisciForm ?>
</div>
        </div>
 </div>
    </div>