<?php $this->headScript()
	->appendFile($this->baseUrl('js/jquery.js'))
	->appendFile($this->baseUrl('js/jquery-ui.js'))
	->captureStart() ?>
         var today = new Date();
         var dd = today.getDate();
         var mm = today.getMonth() + 1;
         var yyyy = today.getFullYear();
         if(dd<10) dd='0'+dd ;
         if(mm<10) mm='0'+mm;
         today = dd + "-" + mm + "-" + yyyy;
         $(function() {
            $( ".date" ).datepicker({
            dateFormat: "dd-mm-yy",
            minDate: today 
            });
         });
<?php $this->headScript()->captureEnd() ?>
         
<h3>Modifica l'offerta selezionata</h3>
<br class="clr"/>
<?php echo $this->modoffertaForm ?>