<?php $this->headScript()
	->appendFile($this->baseUrl('js/jquery.js'))
	->appendFile($this->baseUrl('js/jquery-ui.js'))
        ->appendFile($this->baseUrl('js/date.js')) ?>

         
<h3>Modifica l'offerta selezionata</h3>
<p>Fare attenzione all'inserimento del prezzo e della tipologia di sconto. 
   <br>Il sistema gestisce solo sconti di tipo percentuale(10%,50%,...) e di tipo 3x2(6x3,4x2,..).
   <br>Quindi inserire i caratteri correttamente,utilizzando il % per le percentuali e la x per il 3x2.
   <br>Il prezzo è inteso come originale prima dello sconto. Nel caso 3x2 va inserito il prezzo totale dei prodotti
   senza sconto ,quindi sarà 3 volte il prezzo originale del singolo prodotto.
   <br><b>ATTENZIONE:Se non si inserisce una nuova immagine,verrà lasciata la precendente.</b>
</p>
<?php echo $this->modoffertaForm ?>