<div class="mainBody container">
    <div class="well well-small" style="margin-top: 20px">
        <div id="gallery" style=" width: 30%; float: left; margin-right: 50px">
                <a href="themes/images/products/large/f1.jpg" title="Fujifilm FinePix S2950 Digital Camera">
				<img src="<?=$this->baseUrl('img/prodotti/2.jpg')?>" style="width:100%" alt="Foto prodotto"/>
                </a>
		</div>
                <div style="width: 100%;">
				<h3>Nikon</h3>
				<hr class="soft"/>
				<p>DESCRIZIONE</p>
                                <p>ragione</p>
                                <p>tipologia</p>
                                <p>localizzazione</p>
				<br class="clr"/>
			<a href="#" name="detail"></a>
			<hr class="soft"/>
		</div>
    </div>
    
    <div class="well well-small">
        <div id="gallery" style=" width: 30%; float: left; margin-right: 50px">
                <a href="themes/images/products/large/f1.jpg" title="Fujifilm FinePix S2950 Digital Camera">
				<img src="<?=$this->baseUrl('img/prodotti/2.jpg')?>" style="width:100%" alt="Foto prodotto"/>
                </a>
		</div>
                <div style="width: 100%;">
				<h3>Adidas</h3>
				<hr class="soft"/>
				<p>DESCRIZIONE</p>
                                <p>ragione</p>
                                <p>tipologia</p>
                                <p>localizzazione</p>
				<br class="clr"/>
			<a href="#" name="detail"></a>
			<hr class="soft"/>
		</div>
    </div>
</div>