<div class="mainBody container">
    <?php foreach ($this->aziende as $a) :?>
    <div class="well well-small" style="margin-top: 20px">
        <div id="gallery" style=" width: 30%; float: left; margin-right: 50px">
				<img src="<?=$this->baseUrl('img/prodotti/'.$a->logo)?>" style="width:100%" alt="Logo azienda"/>
		</div>
                <div style="width: 100%;">
				<h3><?= $a->nome ?></h3>
				<hr class="soft"/>
				<p><?= $a->descrizione ?></p>
                                <p><?= $a->ragione ?></p>
                                <p><?= $a->tipologia ?></p>
                                <p><?= $a->localizzazione ?></p>
				<br class="clr"/>
			<a href="#" name="detail"></a>
			<hr class="soft"/>
		</div>
    </div>
    <?php endforeach ?>
    
    <div>
    <?php if($this->aziende instanceof Zend_Paginator) {
	  		echo $this->paginationControl($this->aziende,'Sliding','public/_paginator.phtml');
	  } 
          ?>
    </div>
</div>