<div class="mainBody container">
    <?php foreach ($this->aziende as $a) :?>
    <div class="well well-small marsu">
        <div id="gallery" class="logoa">
            <img src="<?=$this->baseUrl('img/aziende/'.$a->logo)?>" class="larg" alt="Logo azienda"/>
		</div>
        <div class="larg">
				<h3><?= $a->nome ?></h3>
				<hr class="soft"/>
				<p><?= $a->descrizione ?></p>
                                <p><b>Ragione sociale: </b><?= $a->ragione ?></p>
                                <p><b>Tipologia: </b><?= $a->tipologia ?></p>
                                <p><b>Localizzazione: </b><?= $a->localizzazione ?></p>
				<br class="clr"/>
			<a href="#" name="detail"></a>
			<hr class="soft"/>
		</div>
    </div>
    <?php endforeach ?>
    
    <div class="centro">
    <div class="pagination">
    <?php if($this->aziende instanceof Zend_Paginator) {
	  		echo $this->paginationControl($this->aziende,'Sliding','public/_paginator.phtml');
	  } 
          ?>
    </div>
    </div>
</div>