<?php $this->headScript()
	->appendFile($this->baseUrl('js/jquery.js'))
	->appendFile($this->baseUrl('js/jquery-ui.js'))
	->captureStart() ?>
  $( function() {
    $( "#accordion" ).accordion();
  } );
<?php $this->headScript()->captureEnd() ?>
  
<div class="container">
    <h1>FAQ</h1>
    <hr class="soften"/>
    <div id="accordion">
        <?php foreach ($this->faq as $faq) :?>
            <h3><?=$faq->domanda?></h3>
            <div><p><?=$faq->risposta?></p></div>
        <?php endforeach ?>
    </div>
</div>