<div id="mainBody">
<div class="container">
<h1>FAQ</h1>
<hr class="soften"/>	
<div class="accordion" id="accordion2">
        <?php foreach ($this->faq as $faq) :?>
        <div class="accordion-group">
            <div class="accordion-heading">    
                <?php echo '<h4><a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapse'. $faq->id . '">' . $faq->domanda . '</a></h4>' ?>
            </div>
            <?php echo '<div id="collapse' . $faq->id . '" class="accordion-body collapse"  >' ?>
            <div class="accordion-inner">
                <?php echo '<p>' . $faq->risposta . '</p>' ?>
            </div>
	</div>
    	<?php endforeach ?>
</div>

  </div>
</div>

<script src="<?=$this->baseUrl('js/jquery.js')?>" type="text/javascript"></script>
<script src="<?=$this->baseUrl('js/bootstrap.min.js')?>" type="text/javascript"></script>
<script src="<?=$this->baseUrl('js/google-code-prettify/prettify.js')?>"></script>
<script src="<?=$this->baseUrl('js/bootshop.js')?>"></script>
<script src="<?=$this->baseUrl('js/jquery.lightbox-0.5.js')?>"></script>
<script src="<?=$this->baseUrl('js/theamswitcher.js')?>" type="text/javascript" charset="utf-8"></script>