<div class="mainBody container">
<img style="width:100%; margin-top: 20px" src="<?=$this->baseUrl('img/home.jpg')?>" alt=""/>



<div style="padding: 20px">
    <h4 style="text-align: center">Benvenuti!</h4>
    <p>Questo sito ti permette di cercare offerte su varie tipologie di 
                prodotto. Vi è una sezione offerte, nella quale è possibile 
                visualizzare tutte le offerte disponibili, ed inoltre 
                effettuare ricerche in base alla tipologia di 
                prodotto/servizio.  Nella sezione aziende vi è un elenco dei 
                vari marchi commerciali presenti. E' possibile registrarsi 
                allo scopo di poter ottenere il coupon relativo all'offerta a 
                cui si è interessati. Per ulteriori informazioni visitare la 
                sezione FAQ.</p>
</div>



<div>		
			<div class="well well-small">
			<h4>Le offerte più recenti </h4>
			<div class="row-fluid">
			<div id="featured" class="carousel slide">
			<div class="carousel-inner">
			  <div class="item active">
			  <ul class="thumbnails">
                                <?php for($i=0;$i<4;$i++) :?>
				<li class="span3">
				  <div class="thumbnail">
				  <i class="tag"></i>
					<a href="
                                            <?= $this->url(array(
                                            'controller' => 'public',
                                            'action'     => 'offsing',
                                            'id'         => $this->new[$i]->id
                                            ), 
                                            'default',true
                                            ); 
                                            ?>"><img src="<?=$this->baseUrl('img/prodotti/'.$this->new[$i]->immagine)?>" alt="">
					<div class="caption">
					  <h5><?= $this->new[$i]->nome ?></h5>
					  <h4><a class="btn" href="product_details.html">VEDI</a> <span class="pull-right"><?= $this->new[$i]->prezzo ?>€</span></h4>
					</div>
                                        </a>
				  </div>
				</li>
                                <?php endfor ?>
                          </ul>
			  </div>
			   <div class="item">
			  <ul class="thumbnails">
                                <?php for($i=4;$i<8;$i++) :?>
				<li class="span3">
				  <div class="thumbnail">
				  <i class="tag"></i>
					<a href="
                                            <?= $this->url(array(
                                            'controller' => 'public',
                                            'action'     => 'offsing',
                                            'id'         => $this->new[$i]->id
                                            ), 
                                            'default',true
                                            ); 
                                            ?>"><img src="<?=$this->baseUrl('img/prodotti/'.$this->new[$i]->immagine)?>" alt="">
					<div class="caption">
					  <h5><?= $this->new[$i]->nome ?></h5>
					  <h4><a class="btn" href="product_details.html">VEDI</a> <span class="pull-right"><?= $this->new[$i]->prezzo ?>€</span></h4>
					</div>
                                        </a>
				  </div>
				</li>
                                <?php endfor ?>
                          </ul>
			  </div>
			  </div>
			  <a class="left carousel-control" href="#featured" data-slide="prev">‹</a>
			  <a class="right carousel-control" href="#featured" data-slide="next">›</a>
			  </div>
			  </div>
		</div>
    
                <h4>Più scaricati dai nostri clienti </h4>
			  <ul class="thumbnails">
				<?php foreach ($this->scaricate as $s) :?>
				<li class="span3">
				  <div class="thumbnail">
				  <i class="tag"></i>
					<a href="
                                            <?= $this->url(array(
                                            'controller' => 'public',
                                            'action'     => 'offsing',
                                            'id'         => $s->id
                                            ), 
                                            'default',true
                                            ); 
                                            ?>"><img src="<?=$this->baseUrl('img/prodotti/'.$s->immagine)?>" alt="">
					<div class="caption">
					  <h5><?= $s->nome ?></h5>
					  <h4><a class="btn" href="product_details.html">VEDI</a> <span class="pull-right"><?= $s->prezzo ?>€</span></h4>
					</div>
                                        </a>
				  </div>
				</li>
                                <?php endforeach ?>
			  </ul>
</div>
</div>

<!-- TODO spostare in bootstrap.php -->
<script src="<?=$this->baseUrl('js/jquery.js')?>" type="text/javascript"></script>
<script src="<?=$this->baseUrl('js/bootstrap.min.js')?>" type="text/javascript"></script>
<script src="<?=$this->baseUrl('js/bootshop.js')?>"></script>
