<div id="carouselBlk">
	<div id="myCarousel" class="carousel slide">
		<div class="carousel-inner">
		  <div class="item active">
		  <div class="container">
			<a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'offsing',), 
                        'default',true);?>">
                            <img style="width:33%;" src="img/carousel/1.jpg" alt=""/>
                            <div>
				  <h4>Second Thumbnail label</h4>
				  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            </div>
                        </a>
		  </div>
		  </div>
		  <div class="item">
		  <div class="container">
			<a href="register.html"><img style="width:33%;" src="img/carousel/2.jpg" alt=""/></a>
				<div class="carousel-caption">
				  <h4>Second Thumbnail label</h4>
				  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
				</div>
		  </div>
		  </div>
		  <div class="item">
		  <div class="container">
			<a href="register.html"><img style="width:33%;" src="img/carousel/3.jpg" alt=""/></a>
			<div class="carousel-caption">
				  <h4>Second Thumbnail label</h4>
				  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
				</div>
			
		  </div>
		  </div>
		   <div class="item">
		   <div class="container">
			<a href="register.html"><img style="width:33%;" src="img/carousel/4.jpg" alt=""/></a>
			<div class="carousel-caption">
				  <h4>Second Thumbnail label</h4>
				  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
				</div>
		   
		  </div>
		  </div>
		   <div class="item">
		   <div class="container">
			<a href="register.html"><img style="width:33%;" src="img/carousel/5.jpg" alt=""/></a>
			<div class="carousel-caption">
				  <h4>Second Thumbnail label</h4>
				  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
			</div>
		  </div>
		  </div>
		   <div class="item">
		   <div class="container">
			<a href="register.html"><img style="width:33%;" src="img/carousel/6.jpg" alt=""/></a>
			<div class="carousel-caption">
				  <h4>Second Thumbnail label</h4>
				  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
				</div>
		  </div>
		  </div>
		</div>
		<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
		<a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
	  </div> 
</div>

<div style="padding: 20px">
    <h4 style="text-align: center">Benvenuti!</h4>
    <p>Questo sito ti permette di cercare offerte su varie tipologie di 
                prodotto. Vi è una sezione offerte, nella quale è possibile 
                visualizzare tutte le offerte disponibili, ed inoltre 
                effettuare ricerche in base alla tipologia di 
                prodotto/servizio.  Nella sezione aziende vi è un elenco dei 
                vari marchi commerciali presenti. E' possibile registrarsi 
                allo scopo di poter ottenere il coupon relativo all'offerta a 
                cui si è interessati. Per ulteriori informazioni visitare la 
                sezione FAQ.</p>
</div>

<!-- TODO spostare in bootstrap.php -->
<script src="js/jquery.js" type="text/javascript"></script>
<script src="js/bootstrap.min.js" type="text/javascript"></script>
<script src="js/google-code-prettify/prettify.js"></script>
<script src="js/bootshop.js"></script>
<script src="js/jquery.lightbox-0.5.js"></script>
<script src="js/theamswitcher.js" type="text/javascript" charset="utf-8"></script>