<div>
    <h3 style="text-align: center">Login</h3>		
	<div class="row">
		<div> &nbsp;</div>
                <div>
                    <div class="well" style="width: 20%; margin: auto">
			<?php echo $this->loginForm ?>
		</div>
		</div>
	</div>
    
    <p style="text-align: center">Non hai ancora un account? <a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'registrati',), 
                        'default',true);?>">REGISTRATI</a></p>
	
</div>