<div>
    <h3 style="text-align: center">Login</h3>		
	<div class="row">
		<div> &nbsp;</div>
                <div>
                    <div class="well" style="width: 20%; margin: auto">
			<form>
			  <div class="control-group">
				<label class="control-label" for="inputUsername1">Username</label>
				<div class="controls">
				  <input  type="text" id="inputUsername1" placeholder="Username">
				</div>
			  </div>
			  <div class="control-group">
				<label class="control-label" for="inputPassword1">Password</label>
				<div class="controls">
				  <input type="password"  id="inputPassword1" placeholder="Password">
				</div>
			  </div>
			  <div class="control-group">
				<div class="controls">
				  <button type="submit" class="btn">Entra</button>
				</div>
			  </div>
			</form>
		</div>
		</div>
	</div>
    
    <p style="text-align: center">Non hai ancora un account? <a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'registrati',), 
                        'default',true);?>">REGISTRATI</a></p>
	
</div>