<div id="mainBody">
    <div class="container">
	<div class="row">
            <div id="sidebar" class="span3">
                <div class="well">
                     <?php echo $this->ricercaForm ?>
                </div>
    
            </div>

           <div class="span9">
              <ul class="thumbnails">
                            <?php foreach ($this->offerte as $offerta) :?>
				<li class="span3">
				  <div class="thumbnail">
					<a  href="<?= $this->url(array(
                                            'controller' => 'public',
                                            'action'     => 'offsing',
                                            ), 
                                            'default',true
                                            ); 
                                            ?>"><img src="<?=$this->baseUrl('img/prodotti/1.jpg')?>"/></a>
					<div class="caption">
					<?php echo  '<h5>'.$offerta->nome.'</h5>' ?>
					<?php echo '<p>'.$offerta->descrizione.'</p>'?>
					<?php echo  '<h4 style="text-align:center"><a class="btn" href="">Visualizza</a>'
                                        . '<a class="btn" href="">'.$offerta->prezzo.'€</a> '
                                        . '<a class="btn btn-primary" href="">-'.$offerta->tipologia.'%</a></h4>'?>
					</div>
				  </div>
				</li>
                            <?php endforeach ?>
	      </ul>
           </div>
        </div>
    </div>
</div>
