<div class="row well" style="width: 80%; margin: auto">
		<div id="gallery" class="span3">
                <a href="themes/images/products/large/f1.jpg" title="Fujifilm FinePix S2950 Digital Camera">
				<img src="img/products/3.jpg" style="width:100%" alt="Foto prodotto"/>
                </a>
		</div>
		<div class="span6">
				<h3>Nome Prodotto Fujifilm Digital Camera</h3>
				<hr class="soft"/>
                                <p>sconto</p>
                                <p style="text-align: right">$222.00</p>
                                <p style="text-align: right">$222.00</p>
				<hr class="soft"/>
				<p>
				DESCRIZIONE 14 Megapixels. 18.0 x Optical Zoom. 3.0-inch LCD Screen. Full HD photos and 1280 x 720p HD movie capture. ISO sensitivity ISO6400 at reduced resolution. 
				Tracking Auto Focus. Motion Panorama Mode. Face Detection technology with Blink detection and Smile and shoot mode. 4 x AA batteries not included. WxDxH 110.2 ×81.4x73.4mm. 
				Weight 0.341kg (excluding battery and memory card). Weight 0.437kg (including battery and memory card).
				</p>
				<br class="clr"/>
			<a href="#" name="detail"></a>
			<hr class="soft"/>
		</div>
			
		<div class="span9" sty>
                    <div id="myTabContent" class="tab-content">
                        <div class="tab-pane fade active in" id="home">
			<h4>Informazioni sul prodotto</h4>
                            <table class="table table-bordered">
				<tbody>
				<tr class="techSpecRow"><th colspan="2">Dettagli del prodotto</th></tr>
				<tr class="techSpecRow"><td class="techSpecTD1">Azienda:</td><td class="techSpecTD2">Fujifilm</td></tr>
				<tr class="techSpecRow"><td class="techSpecTD1">Tipologia:</td><td class="techSpecTD2">Tipologia prodotto</td></tr>
				<tr class="techSpecRow"><td class="techSpecTD1">Inizio promozione:</td><td class="techSpecTD2"> 2011-01-28</td></tr>
				<tr class="techSpecRow"><td class="techSpecTD1">Fine promozione:</td><td class="techSpecTD2"> 5.50" h x 5.50" w x 2.00" l, .75 pounds</td></tr>
				</tbody>
                            </table>
                        </div>
                    </div>
                </div>
</div>