<div class="mainBody container">
    <div id="gallery" class="logoa">
        <img src="<?=$this->baseUrl('img/prodotti/'.$this->offerta->immagine)?>" class="centro" alt="Foto prodotto"/>
		</div>
    <div class="larg">
        			<h3><?= $this->offerta->nome ?></h3>
				<hr class="soft"/>
                                <p>Sconto: <?= $this->offerta->tipologia ?></p>
                                <p class="destra"><?= $this->offerta->prezzo ?>€</p>
				<hr class="soft"/>
				<p><?= $this->offerta->descrizione ?></p>
				<br class="clr"/>
			<hr class="soft"/>
		</div>
			
                <div>
                    <div id="myTabContent" class="tab-content">
                        <div class="tab-pane fade active in" id="home">
			<h4>Informazioni sul prodotto</h4>
                            <table class="table table-bordered">
				<tbody>
				<tr class="techSpecRow"><th colspan="2">Dettagli del prodotto</th></tr>
				<tr class="techSpecRow"><td class="techSpecTD1">Azienda:</td><td class="techSpecTD2"><?= $this->offerta->azienda ?></td></tr>
				<tr class="techSpecRow"><td class="techSpecTD1">Tipologia:</td><td class="techSpecTD2"><?= $this->offerta->categoria ?></td></tr>
				<tr class="techSpecRow"><td class="techSpecTD1">Inizio promozione:</td><td class="techSpecTD2"><?= $this->offerta->inizio ?></td></tr>
				<tr class="techSpecRow"><td class="techSpecTD1">Fine promozione:</td><td class="techSpecTD2"><?= $this->offerta->fine ?></td></tr>
				</tbody>
                            </table>
                        </div>
                    </div>
                </div>
    
    <?php if($this->ruolo == 'user'):?>   
    <?php if($this->coupon == null):?>
        <a class="btn" target="_blank" onclick="setTimeout(function(){
                                                        location.reload(true);
                                                        },500);"
                                        href="<?= $this->url(array(
                                                     'controller' => 'user',
                                                     'action'     => 'coupon',
                                                     'offerta' => $this->offerta->id
                                                        ), 
                                                                  'default',true
                                                       ); 
                                                     ?>">Genera Coupon</a>
    <?php else: ?>
    <p>Hai già usufruito di questa offerta!</p>
    <?php endif ?>  
    <?php endif ?> 
    
    <?php if($this->ruolo == false):?>   
    <a href="<?= $this->url(array(
                                                     'controller' => 'public',
                                                     'action'     => 'login',
                                                        ), 
                                                                  'default',true
                                                       ); 
                                                     ?>">ATTENZIONE! I coupon possono essere acquistati solo da utenti registrati</a>
    <?php endif ?> 

</div>
