<div>
    <h3 style="text-align: center"> Registrazione</h3>	
	<div class="well" style="width: 60%; margin: auto">
	<form class="form-horizontal" >
            
		<div class="control-group">
			<label class="control-label" for="inputFname1">Nome</label>
			<div class="controls">
			  <input type="text" id="inputFname1" placeholder="Nome">
			</div>
		 </div>
            
		 <div class="control-group">
			<label class="control-label" for="inputLnam">Cognome</label>
			<div class="controls">
			  <input type="text" id="inputLnam" placeholder="Cognome">
			</div>
		 </div>
            
                <div class="control-group">
		<label class="control-label">Genere</label>
		<div class="controls">
		<select class="span1" name="days">
			<option value="">-</option>
			<option value="1">M</option>
			<option value="2">F</option>
		</select>
		</div>
		</div>
            
                <div class="control-group">
		<label class="control-label">Età</label>
		<div class="controls">
		  <select class="span1" name="days">
				<option value="">-</option>
					<option value="1">1&nbsp;&nbsp;</option>
					<option value="2">2&nbsp;&nbsp;</option>
					<option value="3">3&nbsp;&nbsp;</option>
					<option value="4">4&nbsp;&nbsp;</option>
					<option value="5">5&nbsp;&nbsp;</option>
					<option value="6">6&nbsp;&nbsp;</option>
					<option value="7">7&nbsp;&nbsp;</option>
			</select>
		</div>
                </div>
            
		<div class="control-group">
		<label class="control-label" for="input_email">Email</label>
		<div class="controls">
		  <input type="text" id="input_email" placeholder="Email">
		</div>
                </div>
            
                <div class="control-group">
		<label class="control-label" for="input_email">Telefono</label>
		<div class="controls">
		  <input type="text" id="input_email" placeholder="Email">
		</div>
                </div>
            
                <div class="control-group">
		<label class="control-label" for="input_email">Username</label>
		<div class="controls">
		  <input type="text" id="input_email" placeholder="Email">
		</div>
                </div>
            
                <div class="control-group">
		<label class="control-label" for="inputPassword1">Password</label>
		<div class="controls">
		  <input type="password" id="inputPassword1" placeholder="Password">
		</div>
                </div>	  
		
                <div class="control-group">
			<div class="controls">
				<input type="hidden" name="email_create" value="1">
				<input type="hidden" name="is_new_customer" value="1">
				<input class="btn btn-large btn-success" type="submit" value="Registrati" />
			</div>
		</div>		
	</form>
</div>

</div>