<div id="mainBody">
   <div class="container">
       <div class="row">
            <div id="sidebar" class="span3">
                    <div class="well">
                       <?php echo $this->ricercaForm ?>
                    </div>
    
            </div>
<!-- a scopo di test -->
            <div class="span9"> 
                 <h3 style="text-align: center"> Test</h3>
    
	           <div class="well" style="width: 40%; margin: auto">
            
	              <?php $off=$this->offerta['azienda'] ?>
                      <?php echo '<p>'.$off.'</p>' ?>
            
                   </div>
    
            </div>
       </div>
   </div>
</div>