<div id="mainBody">
    <div class="container">
	<div class="row">
            <div id="sidebar" class="span3">
                <div class="well">
                     <?php echo $this->ricercaForm ?>
                </div>
    
            </div>

           <div class="span9">
              <ul class="thumbnails">
				<?php foreach ($this->offerte as $s) :?>
				<li class="span3">
				  <div class="thumbnail">
					<a href="
                                            <?= $this->url(array(
                                            'controller' => 'public',
                                            'action'     => 'offsing',
                                            'id'         => $s->id
                                            ), 
                                            'default',true
                                            ); 
                                            ?>"><img src="<?=$this->baseUrl('img/prodotti/'.$s->immagine)?>" alt="">
					  <h5><?= $s->nome ?></h5>
                                        </a>
					<div class="caption">
					  <h4><a class="btn" href="
                                            <?= $this->url(array(
                                            'controller' => 'public',
                                            'action'     => 'offsing',
                                            'id'         => $s->id
                                            ), 
                                            'default',true
                                            ); 
                                            ?>">VEDI</a>
                                            <span class="pull-right"><?= $s->prezzo ?>€</span></h4>
					</div>
				  </div>
				</li>
                                <?php endforeach ?>
			  </ul>
           </div>
        </div>
    </div>
</div>