<?php echo $this->doctype() ?>
<html>
<head>
    <?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headScript(); ?>
</head>
<body>
<div id="wrapper">
<div id="header">
<div class="container padsu">
<!-- Navbar ================================================== -->
<div id="logoArea" class="navbar">
<a id="smallScreen" data-target="#topMenu" data-toggle="collapse" class="btn btn-navbar">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
</a>
  <div class="navbar-inner">
        <?= $this->render('menu.phtml') ?>
  </div>
</div>
</div>
</div>
        
        
        
	<div id="page">
  	  <div id="page-bgtop">
    	<div id="page-bgbtm">
	  	  <?php echo $this->layout()->content; ?>
            <div class="clea">&nbsp;</div>
	    </div>
  	  </div>
	</div>

	
        
        <!-- Footer ================================================================== -->
	<div  id="footerSection">
	<div class="container">
		<p class="pull-right">&copy; COUPONshop</p>
	</div><!-- Container End -->
	</div>
        
        
</div>
</body>
</html>