<a class="brand" href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 >COUPONshop</a>
<form class="form-inline navbar-search" method="post" action="products.html" >
		<input id="srchFld" class="srchTxt" type="text" />
                    <select class="srchTxt">
			<option>TUTTO</option>
			<option>ABBIGLIAMENTO </option>
			<option>ALIMENTI </option>
			<option>CURA DELLA PERSONA </option>
			<option>ARTICOLI SPORTIVI </option>
			<option>LIBRI </option>
                    </select> 
		  <button type="submit" id="submitButton" class="btn btn-primary">Vai</button>
</form>


<ul id="topMenu" class="nav pull-right">
        <li class=""><a href="
                        <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'offerte',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 >Offerte</a></li>
	 <li class=""><a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'aziende',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 >Aziende</a></li>
	 <li class=""><a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'faq',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 >FAQ</a></li>
	 <li class=""><a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'login',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 style="padding-right:0"><span class="btn btn-large btn-success">Login</span></a></li>
</ul>
