<div class="well">
        <ul>
            <li><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>">Profilo personale</a></li>
            <li><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'insprom',
                        ), 
                        'default',true
                    ); 
                 ?>">Inserisci nuova promozione</a></li>
            <li><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'gestprom',
                        ), 
                        'default',true
                    ); 
                 ?>">Gestisci promozioni</a></li>
        </ul>
</div>       