<a class="brand" href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 >COUPONshop</a>


<ul id="topMenu" class="nav pull-right">
        <li class=""><a href="
                        <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 >Home</a></li>
        <li class=""><a href="
                        <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'offerte',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 >Offerte</a></li>
	 <li class=""><a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'aziende',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 >Aziende</a></li>
	 <li class=""><a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'faq',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 >FAQ</a></li>
         <?php if($this->ruolo == 'user'):?>         
         <li class=""><a href="
                         <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 >Area Utente</a></li>  
         <?php endif ?>       
         <?php if($this->ruolo == 'staff'):?>         
         <li class=""><a href="
                         <?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 >Area Staff</a></li>
         <?php endif ?>
         <li class=""><a href="
                         <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'gestazie',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 >Area Admin</a></li>
         <?php if($this->ruolo == false):?>        
	 <li class=""><a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'login',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 style="padding-right:0"><span class="btn btn-large btn-success">Login</span></a></li>
         <?php endif ?>        
         <?php if($this->ruolo == 'staff' || $this->ruolo == 'user' || $this->ruolo == 'admin'):?>       
         <li class=""><a href="
                         <?= $this->url(array(
                        'controller' => $this->ruolo,
                        'action'     => 'logout',
                        ), 
                        'default',true
                    ); 
                 ?>"
                 style="padding-right:0"><span class="btn btn-large btn-success">Logout</span></a></li> 
        <?php endif ?>         
</ul>
