<div class="well">
        <ul>
            <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'gestazie',
                        ), 
                        'default',true
                    ); 
                 ?>">Gestisci aziende</a></li>
            <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'insazie',
                        ), 
                        'default',true
                    ); 
                 ?>">Inserisci una nuova azienda</a></li>
            <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'gestuser',
                        ), 
                        'default',true
                    ); 
                 ?>">Gestisci utenti</a></li>
            <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'insuser',
                        ), 
                        'default',true
                    ); 
                 ?>">Inserisci nuovo staff</a></li>
            <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'gesttip',
                        ), 
                        'default',true
                    ); 
                 ?>">Gestione tipologie</a></li>
            <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'instip',
                        ), 
                        'default',true
                    ); 
                 ?>">Inserisci una nuova tipologia</a></li>
            <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'gestfaq',
                        ), 
                        'default',true
                    ); 
                 ?>">Gestione FAQ</a></li>
            <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'insfaq',
                        ), 
                        'default',true
                    ); 
                 ?>">Inserimento FAQ</a></li>
            <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'geststat',
                        ), 
                        'default',true
                    ); 
                 ?>">Gestione statistiche</a></li>
            <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'geststaff',
                        ), 
                        'default',true
                    ); 
                 ?>">Assegnazione aziende allo staff</a></li>
        </ul>
</div>       


