<head>
        <?= $this->headTitle(); ?>
</head>
<body>
    <p><b>Prodotto:</b> <?= $this->offerta->nome ?></p>
    <p><b>Descrizione:</b> <?= $this->offerta->descrizione ?></p>
    <p><b>Username:</b> <?= $this->utente->username ?></p>
    <p><b>Nome:</b> <?= $this->utente->nome ?></p>
    <p><b>Cognome:</b> <?= $this->utente->cognome ?></p>
    <p><b>Id coupon:</b> <?= $this->coupon->id ?></p>
    <p><b>Dal:</b> <?= $this->offerta->inizio ?></p>
    <p><b>Al:</b> <?= $this->offerta->fine ?></p>
</body>
