<h3>Assegna un'azienda ad un membro dello staff</h3>
<?php if($this->assegnata):?>
<?php echo '<h4 style="color:red">L\'azienda '.$this->azienda.' è stata assegnata al membro '.$this->staff.'</h4>'?>
<?php endif ?>
<?php if($this->esistente):?>
<?php echo '<h4 style="color:red">Impossibile! L\'azienda '.$this->azienda.' è  già stata assegnata al membro '.$this->staff.'</h4>'?>
<?php endif ?>
<br class="clr"/>
<?php echo $this->gestionestaffForm ?>
