<h3>Gestisci gli utenti inseriti</h3>
<?php if($this->elimina):?>
<?php echo '<h4 style="color:red">Utente '.$this->user.' eliminato</h4>'?>
<?php endif ?>
<?php if($this->modifica):?>
<?php echo '<h4 style="color:red">Utente '.$this->user.' modificato</h4>'?>
<?php endif ?>
<br class="clr"/>
<ul class="thumbnails">
                            <?php foreach ($this->utenti as $utente) :?>
				<li class="span9">
				  <table class="well">
                                      <tr>
                                        <td class="span6">
                                           <?php echo '<p><b>'.$utente->username.'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nome: </b>'.$utente->nome.'&nbsp;&nbsp;<b>Cognome: </b>'.$utente->cognome.'</p>'?>
					  <br class="clr"/>
				         </td>
                                      </tr>
                                      <tr>
                                          <td>
                                              <h4><a class="btn" href="<?= $this->url(array(
                                                     'controller' => 'admin',
                                                     'action'     => 'moduser',
                                                     'username'   => $utente->username,
                                                        ), 
                                                                  'default',true
                                                       ); 
                                                     ?>">Modifica</a>
                                                  <a class="btn" href="<?= $this->url(array(
                                                     'controller' => 'admin',
                                                     'action'     => 'eliminauser',
                                                     'username'   => $utente->username,
                                                        ), 
                                                                  'default',true
                                                       ); 
                                                     ?>">Elimina</a>
                                              </h4>
                                          </td>
                                      </tr>
				  </table>
				</li>
                            <?php endforeach ?>
</ul>

<div class="centro">
    <div class="pagination">
    <?php if($this->utenti instanceof Zend_Paginator) {
	  		echo $this->paginationControl($this->utenti,'Sliding','admin/_paginator.phtml');
	  } 
          ?>
    </div>
</div>